SkyBlog/config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  get 'home/index'

  root 'blog_posts#index'

end

SkyBlog/app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

SkyBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SkyBlog/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :publishdate)
    end
end

SkyBlog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

SkyBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

SkyBlog/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

SkyBlog/app/helpers/home_helper.rb
module HomeHelper
end

SkyBlog/app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <b>Tiêu đề</b><br>
    <%= f.text_field :title, :class => 'form-control', :style => 'width: 100%' %>
  </div>
  <div class="form-group">
    <b>Nội dung</b><br>
    <%= f.text_area :content, :class => 'form-control', :rows => '15' %>
  </div>
  <div class="form-group">
    <b>Publish Date</b><br>
    <%= f.datetime_select :publishdate %>
  </div>
    <div class="form-group ">
      <input class="btn btn-primary" type="submit" name="commit" value="Submit">
    </div>
<% end %>

SkyBlog/app/views/blog_posts/edit.html.erb
<div class="container">
  <h1 style="color: #2288bb">Chỉnh sửa nội dung</h1>
  <%= render 'form' %>
  <%= link_to 'Show', @blog_post %> |
  <%= link_to 'Back', blog_posts_path %>
</div>

SkyBlog/app/views/blog_posts/index.html.erb
<button class="btn btn-default" style="float: right;">
  <%= link_to 'Tạo bài viết mới', new_blog_post_path %>
</button>

<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <h1 style="color:#2288bb; padding-left: 15px; ">Danh sách bài viết</h1>
    <% @blog_posts.each do |blog_post| %>
        <div class="col-xs-12">
          <div>
            <h3>
              <%= blog_post.title %>
            </h3>
            <h6>
              <%= blog_post.publishdate.strftime('%b %d, %Y') %>
            </h6>
          </div>

          <div>
            <%= raw(blog_post.content).truncate(358) %>
          </div>

          <div class="text-center">
            <%= link_to "Show", blog_post %>
          </div>
          <br>
        </div>
    <% end %>
  </div>
</div>

SkyBlog/app/views/blog_posts/new.html.erb
<div class="container">
  <h1>Tạo mới blog</h1>
  <%= render 'form' %>
  <%= link_to 'Back', blog_posts_path %>
</div>

SkyBlog/app/views/blog_posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h3><%= @blog_post.title %></h3>

  <p>
    <%= @blog_post.content %>
  </p>
  <p>
    <%= @blog_post.publishdate %>
  </p>

  <%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
  <%= link_to 'Back', blog_posts_path %>
</div>

SkyBlog/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

SkyBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>